
### GET TOKEN
# @name getToken

POST https://id.twitch.tv/oauth2/token
Content-Type: application/x-www-form-urlencoded

client_id={{$dotenv CLIENT_ID}}&client_secret={{$dotenv SECRET}}&grant_type=client_credentials



### Get USer info
# @name getUserInfo

@streamer_username = fboucheros

GET https://api.twitch.tv/helix/users?login={{streamer_username}}
Client-Id: {{$dotenv CLIENT_ID}}
Authorization: Bearer {{getToken.response.body.access_token}}


### Get videos
GET https://api.twitch.tv/helix/videos?user_id={{getUserInfo.response.body.data[0].id}}&first=5
Client-Id: {{$dotenv CLIENT_ID}}
Authorization: Bearer {{getToken.response.body.access_token}}
