name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fboucher/cloudbot:$(date +%s)

    - name: Docker Login
      uses: docker/login-action@v1.6.0
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASSWORD}}
        logout: true
    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USER}}/cloudbot








